# generated by datamodel-codegen:
#   filename:  parsed_factsheet_schema.json
#   timestamp: 2026-04-07T09:42:40+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MarketExposureItem(BaseModel):
    name: str | None
    percentage: float | None


class TopHolding(BaseModel):
    name: str | None
    percentage: float | None


class IndustryExposureItem(BaseModel):
    name: str | None
    percentage: float | None


class Model(BaseModel):
    isin: str | None
    name: str | None
    documentDate: str | None
    marketExposure: list[MarketExposureItem] = Field(..., max_length=10, min_length=10)
    topHoldings: list[TopHolding] = Field(..., max_length=10, min_length=10)
    industryExposure: list[IndustryExposureItem] = Field(
        ..., max_length=10, min_length=10
    )
